import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { getLocale, getMessages } from "next-intl/server";
import { auth } from "auth";
import { NextIntlClientProvider } from "next-intl";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import { NextThemesProviderRoot } from "./next-themes-provider-root";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  const session = await auth();

  return (
    <html
      lang="en"
      className={cn("h-full antialiased", "font-sans", inter.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <NextThemesProviderRoot>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <SessionProvider session={session}>
              <Toaster />
              {children}
            </SessionProvider>
          </NextIntlClientProvider>
        </NextThemesProviderRoot>
      </body>
    </html>
  );
}
